apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-try-deployment
  labels:
    app: ecom-try
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-try
  template:
    metadata:
      labels:
        app: ecom-try
    spec:
      containers:
        - name: ecom-try
          image: 236604669997.dkr.ecr.us-east-1.amazonaws.com/roman:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80