apiVersion: v1
kind: Service
metadata:
  name: ecom-try-service
  labels:
    app: ecom-try
spec:
  type: ClusterIP
  selector:
    app: ecom-try
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
